### ISSUE TITLE
Make instance migration logic more consistent

### ISSUE THREAD

**Issue by markylaing** [lxc/lxd#9789]
Various improvements to the consistency of instance migration logic was discussed in #9706 but these were not implemented in #9780. 

In summary:
- [ ] Instances should be frozen during migration if the underlying driver does not support it (i.e. if `RunningCopyFreeze=true`). This check is already performed in `CreateInstanceFromCopy` but is not accounted for in `MigrateInstance`. (See https://github.com/lxc/lxd/issues/9706#issuecomment-995595000).
- [ ] The value of `RunningCopyFreeze` should be `true` for the `lvm` driver. (See https://github.com/lxc/lxd/issues/9706#issuecomment-996021403).
- [ ] `btrfs` and `zfs` should use fast snapshots as the source of the migration. This is already performed for backups (again see https://github.com/lxc/lxd/issues/9706#issuecomment-995595000).

**Comment by markylaing** [comment]
@stgraber I wasn't clear on this from the discussion of the previous issue: Should instances *always* be frozen if `--allow-inconsistent` is false?

**Comment by stgraber** [comment]
It should only be done when we have no other alternatives. For zfs, btrfs, we can get a cheap, consistent snapshot so don't need to. For dir, ceph and lvm, those we'd need to freeze the source during transfer.

**Comment by stgraber** [comment]
@markylaing assigned it to you for when you have some time to look at it.

I think the plan is:
 - On btrfs and zfs, when dealing with rsync migration, generate a temporary snapshot and use that as the source, never freeze the instance
 - On everything else, unless AllowInconsistent is set, freeze the source instance during the migration
 - Make sure that we have good error handling and revert logic. A failed migration absolutely needs to cleanup any leftover snapshot and restore the instance to running state.
